CREATE TABLE TESTCASES
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT NOT NULL,
    DESCRIPTION TEXT,
    DATA        JSON,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USERS
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME    TEXT NOT NULL,
    PASSWORD    TEXT NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);