CREATE TABLE TESTCASES
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT NOT NULL,
    DESCRIPTION TEXT,
    DATA        TEXT,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);